"""Add email fields: cc, bcc, attachments, is_draft, is_sent, reply_to_id, in_reply_to

Revision ID: 08448ffbc1e2
Revises: 486617d24348
Create Date: 2026-07-02 13:50:15.051129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08448ffbc1e2'
down_revision = '486617d24348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cc', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('bcc', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('attachments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reply_to_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('in_reply_to', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_column('in_reply_to')
        batch_op.drop_column('reply_to_id')
        batch_op.drop_column('is_sent')
        batch_op.drop_column('is_draft')
        batch_op.drop_column('attachments')
        batch_op.drop_column('bcc')
        batch_op.drop_column('cc')

    # ### end Alembic commands ###
